Swap To Postgresql
sublinks/sublinks-api pull request #354
Opened 2024-04-23 06:31 UTC by Pdzly

Closes #353

2024-04-23 12:52 UTC, jgrim submitted a review, later dismissed

2024-04-23 12:53 UTC, jgrim commented
We can merge this in once the docker configuration supports it.

2024-04-23 13:10 UTC, DarkArc commented
There seem to be a fair number of odd whitespace changes and some imports that aren't relevant.

It's not a huge deal, but it would be nice to clean those up.

2024-04-23 19:47 UTC, Pdzly commented
I will wait and see if federation swaps over to postgresql too, just for organisational side.

2024-04-24 00:30 UTC, jgrim submitted a review, later dismissed

2024-04-24 01:31 UTC, lazyguru requested changes

2024-04-24 15:35 UTC, jgrim approved these changes

2024-04-26 14:44 UTC, Pdzly commented on .github/dependabot.yml
> -  - package-ecosystem: "gradle"
This f*cked up the automatic checks. As this is in terms, illegal.

2024-04-26 14:44 UTC, merged

2024-04-27 01:47 UTC, lazyguru commented on .github/dependabot.yml
> -  - package-ecosystem: "gradle"
I don't understand what you mean here? By removing this, you remove automatic dependency management of Java packages by Dependabot. Please add it back