#373 Resolves immutable updatedAt column
sublinks/sublinks-api pull request #389
Opened 2024-05-12 22:32 UTC by jgrim

Resolves #373

2024-05-12 22:34 UTC, jgrim commented
@Pdzly I've thought more about this issue. I think we should remove the db triggers and let springboot manage updatedAt for the entities. Rather than removing the annotation I believe we should make the field mutable and allow springboot to handle it. I'd consider updating the annotations for update and create to be driven by the database timestamp like so:

`@UpdateTimestamp(source = SourceType.DB)` & `@CreationTimestamp(source = SourceType.DB)`

2024-05-13 06:11 UTC, Pdzly commented
> @Pdzly I've thought more about this issue. I think we should remove the db triggers and let springboot manage updatedAt for the entities. Rather than removing the annotation I believe we should make the field mutable and allow springboot to handle it. I'd consider updating the annotations for update and create to be driven by the database timestamp like so:
> 
> `@UpdateTimestamp(source = SourceType.DB)` & `@CreationTimestamp(source = SourceType.DB)`

Ok

2024-05-13 07:00 UTC, Pdzly commented
Fixed it

2024-05-19 18:00 UTC, lazyguru submitted a review, later dismissed
lgtm

2024-05-22 15:46 UTC, lazyguru requested changes

2024-05-22 15:46 UTC, lazyguru commented on src/main/java/com/sublinks/sublinksapi/community/entities/Community.java
> +  @UpdateTimestamp(source = SourceType .DB)
extra space here between `SourceType` and `.DB`

2024-05-23 17:18 UTC, lazyguru approved these changes

2024-05-23 17:20 UTC, merged